# Generated by Django 4.1.12 on 2023-10-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuitem',
            name='sku_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
