# Generated by Django 4.1.10 on 2023-09-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='polymorphic_ctype',
        ),
    ]
