# Generated by Django 4.1.12 on 2023-11-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuitem',
            name='sku_code',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
