version: '3.8'

services:
  app:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./weedboxy/:/usr/src/weedboxy/
    ports:
      - "8000:8000"
    env_file:
    - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=wboxydb
      - POSTGRES_USER=wbadmin
      - POSTGRES_PASSWORD=Wboxy123
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data:
