version: '3'

services:
  
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=wboxydb
      - POSTGRES_USER=wbadmin
      - POSTGRES_PASSWORD=Wboxy123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

