# Generated by Django 4.1.12 on 2023-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescontact',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicescontact',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
