# Generated by Django 4.2.5 on 2023-10-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_skuitem_sku_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('skuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.skuitem')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.skuitem',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('skuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.skuitem')),
                ('is_active', models.BooleanField()),
                ('package_items', models.ManyToManyField(blank=True, related_name='package_items', to='packages.packageitem')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.skuitem',),
        ),
    ]
