# Generated by Django 4.1.10 on 2023-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='package_item',
            field=models.ManyToManyField(blank=True, related_name='package_items', to='packages.packageitem'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
