# Generated by Django 4.1.10 on 2023-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
