# Generated by Django 4.1.10 on 2023-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packageitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.TextField(),
        ),
    ]
