# Generated by Django 4.1.10 on 2023-09-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packageitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_item',
            new_name='package_items',
        ),
    ]
