# Generated by Django 4.1.12 on 2023-11-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
