# Generated by Django 4.0.6 on 2023-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state_province_region', models.CharField(default='', max_length=255)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
