# Generated by Django 4.1.12 on 2023-10-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_skuitem_sku_code'),
        ('users', '0004_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.order'),
            preserve_default=False,
        ),
    ]
