# Generated by Django 4.1.10 on 2023-10-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0005_rename_package_item_package_package_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationPlan',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages.package')),
                ('image', models.ImageField(upload_to='img/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'abstract': False,
            },
            bases=('packages.package',),
        ),
    ]
