# Generated by Django 4.1.12 on 2023-11-02 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationPlan',
            fields=[
                ('skuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.skuitem')),
                ('image', models.ImageField(upload_to='img/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.skuitem',),
        ),
        migrations.CreateModel(
            name='StagesCultivationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('cultivation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.cultivationplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('cultivation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.cultivationplan')),
            ],
        ),
    ]
