# Generated by Django 4.1.10 on 2023-10-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagesCultivationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cultivation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.cultivationplan')),
            ],
        ),
    ]
