# Generated by Django 4.1.10 on 2023-10-11 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0002_stagescultivationplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagescultivationplan',
            name='step',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
